name: auximity.com
favicon: null
layout_spectrum: 0.5573368747718632
typography_spectrum: 0.6890055472031236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7396956926677376
  lightness: 0.7111605086829513
  saturation: 0.25825372035615146
  rhythmicContrast: 0.2582732434384525
purpose: []
