name: auximity.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75041
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#262a2d'
    - '#28c121'
    - '#a0dd9b'
    - '#949799'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
